services:
  backend:
    build: 
      context: ./backend
      target: development
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app
      - DATABASE_URL=mysql://apiuser:${DB_PASSWORD}@db:3306/carmonitoring
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      retries: 3
      timeout: 10s

  frontend:
    build: 
      context: ./frontend
      target: development
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"
    environment:
      - VITE_API_URL=http://localhost:5000

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=carmonitoring
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=sonny
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "43306:3306" # Expose MySQL on port 43306
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-usonny", "-p$$DB_PASSWORD"]
      interval: 30s
      timeout: 10s
      retries: 5


volumes:
  mysql_data:
