name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'   # Immer die neuste Minor-Version, falls möglich

      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd backend
          pytest

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build with Docker Compose
        run: |
          docker-compose -f docker-compose.ci.yml build

      - name: Run containers
        run: |
          docker-compose -f docker-compose.ci.yml up -d

      - name: Wait for backend to be healthy
        run: |
          for i in {1..15}; do
            docker-compose -f docker-compose.ci.yml exec -T backend bash -c "curl -sf http://localhost:5001/api/health || exit 1" && break
            echo "Warte auf Backend-Startup... ($i/15)"
            sleep 5
          done

      - name: Run backend tests in Docker
        run: |
          docker-compose -f docker-compose.ci.yml exec -T backend pytest

      - name: Shutdown containers
        if: always()
        run: |
          docker-compose -f docker-compose
