name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Debug Python environment
        run: |
          python --version
          pip list

      - name: Run tests
        run: |
          cd backend
          pytest

  build:
    needs: test
    runs-on: ubuntu-latest
    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_USER: postgres
      DB_HOST: database
      DB_NAME: app
      DB_PORT: 5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build with Docker Compose
        run: |
          docker-compose -f docker-compose.ci.yml build

      - name: Run containers
        run: |
          docker-compose -f docker-compose.ci.yml up -d

      - name: Check container status
        run: |
          docker-compose -f docker-compose.ci.yml ps
          
      - name: Debug - View Backend Logs
        run: |
          docker-compose -f docker-compose.ci.yml logs backend

      - name: Install curl in runner
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

      - name: Wait for backend to be healthy
        run: |
          for i in {1..5}; do
            # Direkt vom GitHub Runner aus auf den exponierten Port zugreifen
            if curl -sf http://localhost:5000/api/health; then
              echo "Backend ist gesund!"
              break
            fi
            echo "Warte auf Backend-Startup... ($i/5)"
            sleep 5
            if [ $i -eq 30 ]; then
              echo "Backend-Startup fehlgeschlagen nach 5 Versuchen."
              docker-compose -f docker-compose.ci.yml logs backend
              exit 1
            fi
          done

      - name: Run backend tests in Docker
        run: |
          docker-compose -f docker-compose.ci.yml exec -T backend pytest || {
            echo "Tests fehlgeschlagen. Backend-Logs anzeigen:"
            docker-compose -f docker-compose.ci.yml logs backend
            exit 1
          }

      - name: Shutdown containers
        if: always()
        run: |
          docker-compose -f docker-compose.ci.yml down
